#!/usr/bin/env node
/**
 * Generate a fresh .env file with all required secrets.
 * Run: node scripts/generate-env.js
 */

"use strict";

const crypto = require("crypto");
const fs = require("fs");
const path = require("path");

const envPath = path.join(__dirname, "..", ".env");

if (fs.existsSync(envPath)) {
  console.log("⚠️  .env already exists. Delete it first if you want to regenerate.");
  process.exit(0);
}

const urlEncryptionKey = crypto.randomBytes(32).toString("hex");
const jwtSecret        = crypto.randomBytes(64).toString("hex");
const adminToken       = crypto.randomBytes(32).toString("base64url");

const content = `# Auto-generated by scripts/generate-env.js on ${new Date().toISOString()}
# ⚠️  NEVER commit this file to git!

NODE_ENV=development
BASE_URL=http://localhost

URL_ENCRYPTION_KEY=${urlEncryptionKey}
JWT_SECRET=${jwtSecret}
ADMIN_TOKEN=${adminToken}

API_GATEWAY_PORT=3000
URL_SERVICE_PORT=3001
REDIRECT_SERVICE_PORT=3002
ANALYTICS_SERVICE_PORT=3003
AUTH_SERVICE_PORT=3004

MONGO_URI=mongodb://mongo-primary:27017/url-shortener?replicaSet=rs0
MONGO_URI_SECONDARY=mongodb://mongo-secondary-1:27017,mongo-secondary-2:27017/url-shortener?replicaSet=rs0&readPreference=secondaryPreferred
NUM_SHARDS=3

REDIS_CLUSTER_NODES=redis-node-1:6379,redis-node-2:6379,redis-node-3:6379
REDIS_HOST=redis-node-1
REDIS_PORT=6379
REDIS_URL=redis://redis-node-1:6379

RATE_LIMIT_WINDOW=10
RATE_LIMIT_MAX=100
DDOS_BURST_LIMIT=500
DDOS_BLOCK_DURATION=60

CIRCUIT_BREAKER_THRESHOLD=5
CIRCUIT_BREAKER_TIMEOUT=30

L1_CACHE_TTL_SEC=60
L2_CACHE_TTL_SEC=3600
REDIRECT_L1_CACHE_MAX=50000

ANALYTICS_CONCURRENCY=20
ANALYTICS_BATCH_MS=100

LOG_LEVEL=debug
`;

fs.writeFileSync(envPath, content, "utf8");

console.log("✅ .env generated successfully!");
console.log(`\n🔑 ADMIN_TOKEN: ${adminToken}`);
console.log("   Save this — you'll need it to get a JWT and create API keys.\n");
console.log("📋 Next steps:");
console.log("   1. docker-compose up --build");
console.log("   2. POST https://localhost/auth/token  { adminToken: '<above>' }");
console.log("   3. POST https://localhost/api/url     { longUrl: 'https://...' }");
